AWSTemplateFormatVersion: 2010-09-09
Description: >-
  demo

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  env:
    Type: String

Resources:
  WebControllerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'demo-reporting-svc-${env}'
      CodeUri: dist/web-controller/web-controller.zip
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 256
      Timeout: 300
      Description: Example Lambda
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          TABLE_NAME: !Ref SampleTable
      Events:
        PostViewEvents:
          Type: Api
          Properties:
            Path: /api/rest/view-events
            Method: POST
        DownloadViewEvents:
          Type: Api
          Properties:
            Path: /api/rest/view-events/{guid}
            Method: GET

  SampleTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub 'reporting-svc-${env}'
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
