AWSTemplateFormatVersion: 2010-09-09
Description: >-
  demo

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  env:
    Type: String

Resources:
  WebControllerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "demo-reporting-svc-${env}"
      CodeUri: dist/web-controller/web-controller.zip
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: Example Lambda
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/rest/{guid}/view-events
            Method: GET

  # DynamoDB table to store item: {id: &lt;ID&gt;, name: &lt;NAME&gt;}
  SampleTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: "reporting-svc-${env}"
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
